#!/usr/bin/env python3
"""Generate fleet-cli's airframe catalog from a built PX4-Autopilot tree.

Extracts every airframe the built ROMFS can actually resolve (the union of
etc/init.d/airframes and etc/init.d-posix/airframes — exactly the set
rc.autostart searches), with the @name/@type/@class metadata tags, and
emits the static Rust table in fleet-cli/src/airframes.rs.

Class inference: @class when present, else from the sourced defaults file
(rc.boat_defaults -> Boat, rc.rover_* -> Rover, rc.mc_* -> Copter,
rc.fw_* -> Plane, rc.vtol_* -> VTOL, rc.airship/balloon -> Other).

Category folding for the console's QGC-style groups: Copter / Plane / VTOL /
Rover / Boat / Underwater / Other / Simulator (the model-tagged SITL frames).

Usage: gen_airframes.py [px4-build-etc-dir]
  default PX4 build etc: ../PX4-Autopilot/build/px4_sitl_default/etc
"""

import pathlib
import re
import sys

DEFAULT_ETC = (
    pathlib.Path(__file__).resolve().parents[2].parent / "PX4-Autopilot"
    / "build" / "px4_sitl_default" / "etc"
)

CATEGORY_ORDER = [
    "Copter",
    "Plane",
    "Vtol",
    "Rover",
    "Boat",
    "Underwater",
    "Other",
    "Simulator",
]

CLASS_TO_CATEGORY = {
    "Copter": "Copter",
    "Plane": "Plane",
    "VTOL": "Vtol",
    "Rover": "Rover",
    "Boat": "Boat",
    "Underwater Robot": "Underwater",
    "Airship": "Other",
    "Balloon": "Other",
    "Autogyro": "Other",
    "Simulation": "Simulator",
    "2D Space Robot": "Other",
}

DEFUALTS_CLASS = [
    ("rc.boat_defaults", "Boat"),
    ("rc.rover_ackermann_defaults", "Rover"),
    ("rc.rover_differential_defaults", "Rover"),
    ("rc.rover_defaults", "Rover"),
    ("rc.airship_apps", "Airship"),
    ("rc.balloon_defaults", "Balloon"),
    ("rc.vtol_defaults", "VTOL"),
    ("rc.fw_apps", "Plane"),
    ("rc.fw_defaults", "Plane"),
    ("rc.heli_defaults", "Copter"),
    ("rc.mc_apps", "Copter"),
    ("rc.mc_defaults", "Copter"),
]

SIM_ENGINES = ("gazebo-classic_", "jmavsim_", "sihsim_", "jsbsim_", "none_")

HEADER = """//! PX4 airframe catalog (auto-generated — do not edit by hand).
//!
//! Generated by `fleet/scripts/gen_airframes.py` from the **built**
//! PX4-Autopilot v1.16.2 ROMFS (the union of `etc/init.d/airframes` and
//! `etc/init.d-posix/airframes` — exactly the set PX4's rc.autostart can
//! resolve, so every entry is a SYS_AUTOSTART value this stack can really
//! apply). Names/types/classes come from the airframes' own `@name`,
//! `@type`, `@class` metadata tags — the same tags QGroundControl's airframe
//! browser serves.
//!
//! Regenerate after a PX4 version bump:
//!   python3 fleet/scripts/gen_airframes.py <px4>/build/px4_sitl_default/etc

#![allow(clippy::all)]

/// QGC-style grouping for the console's airframe picker.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AirframeCategory {
    Copter,
    Plane,
    Vtol,
    Rover,
    Boat,
    Underwater,
    Other,
    Simulator,
}

impl AirframeCategory {
    /// Console-facing label (UAV/UGV/USV annotated, QGC browser order).
    pub fn label(self) -> &'static str {
        match self {
            AirframeCategory::Copter => "Multirotor (UAV)",
            AirframeCategory::Plane => "Fixed Wing (UAV)",
            AirframeCategory::Vtol => "VTOL (UAV)",
            AirframeCategory::Rover => "Rover (UGV)",
            AirframeCategory::Boat => "Boat (USV)",
            AirframeCategory::Underwater => "Underwater (UUV)",
            AirframeCategory::Other => "Other",
            AirframeCategory::Simulator => "Simulator (SITL models)",
        }
    }
}

/// One selectable airframe.
#[derive(Debug, Clone, Copy)]
pub struct Airframe {
    /// SYS_AUTOSTART value that selects this airframe at boot.
    pub id: u32,
    /// `@name` from the airframe script.
    pub name: &'static str,
    /// `@type` (frame geometry) from the airframe script.
    pub frame_type: &'static str,
    pub category: AirframeCategory,
    /// SITL model tag (the PX4_SIM_MODEL value that selects this frame at
    /// boot) — posix model airframes only, None for real-vehicle frames.
    pub sim_model: Option<&'static str>,
}

/// The full catalog, sorted by (category, id).
pub static AIRFRAMES: &[Airframe] = &[
"""


def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def parse_airframe(path: pathlib.Path) -> dict | None:
    text = path.read_text(errors="replace")
    m = re.search(r"^#\s*@name\s+(.+)$", text, re.M)
    name = m.group(1).strip() if m else path.stem
    m = re.search(r"^#\s*@type\s+(.+)$", text, re.M)
    ftype = m.group(1).strip() if m else ""
    m = re.search(r"^#\s*@class\s+(.+)$", text, re.M)
    klass = m.group(1).strip() if m else None
    if klass is None:
        for marker, k in DEFUALTS_CLASS:
            if f". ${{R}}etc/init.d/{marker}" in text or marker in text:
                klass = k
                break
    if klass is None:
        klass = "Other"
    category = CLASS_TO_CATEGORY.get(klass, "Other")

    stem = path.stem
    mid = re.match(r"^(\d+)_(.+)$", stem)
    if not mid:
        return None
    aid = int(mid.group(1))
    tail = mid.group(2)
    sim_model = None
    if any(tail.startswith(e) for e in SIM_ENGINES):
        sim_model = tail
        # SITL model frames (gazebo/jmavsim/sih/jsbsim) fold to Simulator
        # EXCEPT the boat, which stays a first-class USV entry.
        if category != "Boat":
            category = "Simulator"
    if klass == "Simulation":
        category = "Simulator"
    return {
        "id": aid,
        "name": name,
        "frame_type": ftype,
        "category": category,
        "sim_model": sim_model,
    }


def main() -> int:
    etc = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_ETC
    entries = {}
    for sub in ("init.d/airframes", "init.d-posix/airframes"):
        d = etc / sub
        if not d.is_dir():
            print(f"missing {d}", file=sys.stderr)
            return 1
        for p in sorted(d.iterdir()):
            m = re.match(r"^(\d+)_", p.name)
            if not m or p.name.endswith(".hil"):
                # .hil files are alternate HIL boot scripts for the same id
                # (1001_rc_quad_x.hil) — not separately selectable.
                continue
            parsed = parse_airframe(p)
            if parsed:
                entries.setdefault(parsed["id"], parsed)

    rows = sorted(entries.values(), key=lambda e: (CATEGORY_ORDER.index(e["category"]), e["id"]))
    out = [HEADER]
    for e in rows:
        cat = f"AirframeCategory::{e['category']}"
        model = f'Some("{esc(e["sim_model"])}")' if e["sim_model"] else "None"
        out.append(
            f'    Airframe {{ id: {e["id"]}, name: "{esc(e["name"])}", '
            f'frame_type: "{esc(e["frame_type"])}", category: {cat}, sim_model: {model} }},'
        )
    out.append("];\n")
    target = pathlib.Path(__file__).resolve().parents[1] / "crates" / "fleet-cli" / "src" / "airframes.rs"
    target.write_text("\n".join(out))
    cats = {}
    for e in rows:
        cats[e["category"]] = cats.get(e["category"], 0) + 1
    print(f"wrote {len(rows)} airframes to {target}")
    print("by category:", ", ".join(f"{k}={v}" for k, v in cats.items()))
    return 0


if __name__ == "__main__":
    sys.exit(main())
