#!/bin/bash
# =============================================================================
# run_sitsim_vehicle.sh <instance> <hil_port> <duration_s>
#
# Per-vehicle rustsitsim runner for mavfleet's real-sim integration (ADR-0001
# step 3: the manager's [sim] command template renders to this wrapper).
#
# Generates a per-vehicle rustsitsim scenario TOML from the I-1 proven-good
# base (ideal sensors, turbulence off) parameterized by instance: HIL TCP
# port, control-plane port (8200+i), duration, RNG seed (100+i, distinct per
# vehicle), then execs sitsim-cli in real-time pacing.
#
# Battery discharge acceleration for the Appendix B ladder test (vehicle 1 at
# 1.6x) is not expressible in rustsitsim v0.1's battery model (enabled/
# capacity_mah only) — documented gap; the ladder is exercised at the PX4
# BATTERY_STATUS level instead.
# =============================================================================
set -eu
INSTANCE="${1:?instance}"
HIL_PORT="${2:?hil_port}"
DURATION="${3:?duration_s}"
API_PORT=$((8200 + INSTANCE))
SEED=$((100 + INSTANCE))
# Geo origin (ADR-0017): the manager exports the scenario [env] origin;
# defaults are the PX4 test field — the same constant rustsitsim pins, so
# the fleet's lat/lon <-> NED conversion and the sim's HIL_GPS anchor can
# never disagree.
ORIGIN_LAT="${RSIM_ORIGIN_LAT:-47.397770}"
ORIGIN_LON="${RSIM_ORIGIN_LON:-8.545580}"
ORIGIN_ALT="${RSIM_ORIGIN_ALT:-500.0}"
# Wind + turbulence (the manager exports the scenario [env] values).
# Defaults keep the pre-propagation behavior: wind 0, turbulence off.
WIND_MS="${RSIM_WIND_MS:-0.0,0.0,0.0}"
TURBULENCE="${RSIM_TURBULENCE:-off}"
# GPS + baro noise (default 0 = the historical noiseless profile; override
# via RSIM_GPS_POS_NOISE_M etc. for experiments). NOTE: the long-idle
# arming fix is NOT sensor noise — it is the manager's per-pair CPU
# pinning (fleet-simctl, 2026-09-09): PX4's SITL sensor timestamps are
# arrival-driven, and lockstep HIL jitter under cross-process CPU
# contention was what railed the EKF2 accel-bias state. Noiseless GPS
# also keeps PX4's EKF2_REQ_HDRIFT (0.3 m/s) stationary-drift check
# trivially green; GPS pos noise of ~0.5 m makes that check fail.
GPS_POS_NOISE="${RSIM_GPS_POS_NOISE_M:-0.0}"
GPS_VERT_NOISE="${RSIM_GPS_VERT_NOISE_M:-0.0}"
GPS_VEL_NOISE="${RSIM_GPS_VEL_NOISE_MS:-0.0}"
BARO_NOISE="${RSIM_BARO_NOISE_M:-0.0}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SITSIM="${FLEET_SITSIM_BIN:-$SCRIPT_DIR/../../sim/target/debug/sitsim-cli}"

CFG_DIR="${FLEET_SIM_CFG_DIR:-$SCRIPT_DIR/../scratch/vsims}"
CFG="$CFG_DIR/vehicle_${INSTANCE}.toml"
mkdir -p "$CFG_DIR"

cat > "$CFG" <<EOF
# Generated by run_sitsim_vehicle.sh (I-1 base, instance $INSTANCE)
[io]
tcp_port = $HIL_PORT
api_port = $API_PORT

[sim]
rate_hz = 200
duration_s = $DURATION
seed = $SEED

[vehicle]
origin = { lat_deg = $ORIGIN_LAT, lon_deg = $ORIGIN_LON, alt_m = $ORIGIN_ALT }

[sensors.imu]
# Realistic BMI088-class noise (rustsitsim config defaults): a noiseless
# IMU leaves EKF2's accel-bias estimate degenerate and arming
# nondeterministic ("Preflight Fail: High Accelerometer Bias" — the same
# zero-noise-starves-the-estimator class as the mag finding, ADR-0012 /
# ADR-0014; verified in rustsitsim's live I-2 flight).
gyro_noise_density = 0.00035
gyro_bias_walk = 0.0
gyro_turnon_sigma = 0.0
gyro_scale_sigma = 0.0
gyro_misalign_deg = 0.0
accel_noise_density = 0.0025
accel_bias_walk = 0.0
accel_turnon_sigma = 0.0
accel_scale_sigma = 0.0
accel_misalign_deg = 0.0

[sensors.mag]
# Empirical: PX4's mag pipeline (calibration/selection upstream of EKF2)
# requires non-constant magnetometer data; a perfectly noiseless mag starves
# it -> EKF2 never fuses mag -> yaw never aligns -> GNSS fusion blocked ->
# no horizontal position -> arming denied. 0.005 G ≈ real sensor noise;
# verified: yaw_align + gnss fusion + xy_valid within ~15 s.
noise_gauss = 0.005
hard_iron_gauss = 0.0

[sensors.baro]
noise_m = $BARO_NOISE
walk_m_per_min = 0.0

[sensors.gps]
rate_hz = 5
latency_ms = 0
pos_noise_m = $GPS_POS_NOISE
pos_noise_vert_m = $GPS_VERT_NOISE
vel_noise_ms = $GPS_VEL_NOISE
lock_s = 0.0

[env]
wind_steady_ms = [$WIND_MS]
turbulence = "$TURBULENCE"
EOF

exec "$SITSIM" scenario-run "$CFG" --speed 1.0 \
    --replay-out "$CFG_DIR/vehicle_${INSTANCE}.replay"
