//! Golden-vector codec tests (SPEC §10.2).
//!
//! Expected byte sequences were generated by `scratch/golden_gen.py` using
//! pymavlink 2.4.49 as an independent oracle, and cross-checked against the
//! PX4-Autopilot v1.16.2 generated headers (`LEN`/`MIN_LEN`/`CRC_EXTRA`).
//! See `golden_vectors.rs` (generated, committed) for the constants.

mod golden_vectors;

use golden_vectors::*;
use sitsim_mavlink::*;

fn sensor_msg() -> HilSensor {
    HilSensor {
        time_usec: 1_000_000,
        xacc: 0.11,
        yacc: -0.22,
        zacc: -9.7103,
        xgyro: 0.001,
        ygyro: -0.002,
        zgyro: 0.003,
        xmag: 0.19,
        ymag: 0.01,
        zmag: 0.46,
        abs_pressure: 1013.25,
        diff_pressure: 4.5,
        pressure_alt: -3.2,
        temperature: 21.5,
        fields_updated: 0x1FFF,
        id: 3,
    }
}

fn hsq_msg() -> HilStateQuaternion {
    HilStateQuaternion {
        time_usec: 1_000_000,
        attitude_quaternion: [0.9998, 0.0, 0.017, 0.0],
        rollspeed: 0.01,
        pitchspeed: -0.02,
        yawspeed: 0.03,
        lat: 473977000,
        lon: 85455000,
        alt: 500_000,
        vx: -3,
        vy: 4,
        vz: -88,
        ind_airspeed: 0,
        true_airspeed: 0,
        xacc: 11,
        yacc: -22,
        zacc: -990,
    }
}

fn gps_msg() -> HilGps {
    HilGps {
        time_usec: 1_000_000,
        lat: 473977011,
        lon: 85455022,
        alt: 500_880,
        eph: 100,
        epv: 150,
        vel: 88,
        vn: 3,
        ve: -4,
        vd: -8,
        cog: 27000,
        fix_type: 3,
        satellites_visible: 10,
        id: 0,
        yaw: 0,
    }
}

fn actuator_msg() -> HilActuatorControls {
    let mut controls = [0f32; 16];
    controls[0] = 0.1;
    controls[1] = -0.2;
    controls[2] = 0.3;
    controls[3] = -0.4;
    HilActuatorControls { time_usec: 1_000_000, controls, mode: 1, flags: 0 }
}

fn command_long_msg() -> CommandLong {
    CommandLong {
        param1: 115.0,
        param2: 5000.0,
        param3: 0.0,
        param4: 0.0,
        param5: 0.0,
        param6: 0.0,
        param7: 0.0,
        command: 511,
        target_system: 2,
        target_component: 1,
        confirmation: 0,
    }
}

fn command_ack_msg() -> CommandAck {
    CommandAck::new(511, 0)
}

/// Byte-exact encode check for every message type, cross-checked against the
/// pymavlink oracle (this is the "cross-check at least one HIL_SENSOR frame
/// against pymavlink's encoding" requirement, applied to the five messages whose
/// current-dialect layout matches PX4 v1.16.2; HIL_ACTUATOR_CONTROLS drifted
/// and is covered by `hil_actuator_controls_px4_layout_offsets`).
#[test]
fn golden_encode_all_messages() {
    let cases: [(Message, u8, &[u8]); 5] = [
        (Message::HilSensor(sensor_msg()), 0, GOLDEN_HIL_SENSOR),
        (Message::HilStateQuaternion(hsq_msg()), 1, GOLDEN_HIL_STATE_QUATERNION),
        (Message::HilGps(gps_msg()), 2, GOLDEN_HIL_GPS),
        (Message::CommandLong(command_long_msg()), 3, GOLDEN_COMMAND_LONG),
        (Message::CommandAck(command_ack_msg()), 4, GOLDEN_COMMAND_ACK),
    ];
    for (msg, seq, golden) in cases {
        let frame = Frame::from_message(&msg, seq, SYS_ID, COMP_ID);
        let bytes = frame.encode();
        assert_eq!(&bytes[..], golden, "encode mismatch for {:?}", msg.msgid());
    }
}

/// The v1-style truncation case: HIL_SENSOR without the extension byte.
/// The decoder zero-fills, so the decoded id is 0 — which is exactly the
/// boot-gate value, and the reason v1-only senders stall PX4 boot while
/// truncated v2 senders do not (SPEC §3.2).
#[test]
fn golden_hil_sensor_truncated_extension() {
    // Reconstruct: full payload minus the trailing `id` byte.
    let msg = sensor_msg();
    let mut full = vec![0u8; HilSensor::FULL_LEN];
    msg.pack_into(&mut full);
    full.truncate(HilSensor::FULL_LEN - 1);
    let frame = Frame { seq: 0, sysid: SYS_ID, compid: COMP_ID, msgid: msg_id::HIL_SENSOR, payload: full };
    assert_eq!(&frame.encode()[..], GOLDEN_HIL_SENSOR_TRUNCATED);

    // And the truncated golden frame decodes back with id = 0.
    let mut p = FrameParser::new();
    p.feed(GOLDEN_HIL_SENSOR_TRUNCATED);
    let frames = p.take();
    assert_eq!(frames.len(), 1);
    match frames[0].decode().unwrap() {
        Message::HilSensor(s) => {
            assert_eq!(s.id, 0);
            assert_eq!(s.time_usec, 1_000_000);
            assert_eq!(s.fields_updated, 0x1FFF);
            assert!((s.zacc - (-9.7103)).abs() < 1e-6);
        }
        _ => panic!("wrong message"),
    }
}

/// Round-trip: golden wire bytes -> parser -> typed message -> field checks.
#[test]
fn golden_decode_roundtrip() {
    let mut p = FrameParser::new();
    p.feed(GOLDEN_HIL_SENSOR);
    p.feed(GOLDEN_HIL_STATE_QUATERNION);
    p.feed(GOLDEN_HIL_GPS);
    p.feed(GOLDEN_HIL_ACTUATOR_CONTROLS);
    p.feed(GOLDEN_COMMAND_LONG);
    p.feed(GOLDEN_COMMAND_ACK);
    let frames = p.take();
    assert_eq!(frames.len(), 6);
    assert_eq!(p.bad_crc_frames, 0);
    assert_eq!(p.unknown_msgid_frames, 0);

    match frames[0].decode().unwrap() {
        Message::HilSensor(s) => {
            assert_eq!(s.time_usec, 1_000_000);
            assert_eq!(s.id, 3);
            assert_eq!(s.fields_updated, 0x1FFF);
            assert!((s.xacc - 0.11).abs() < 1e-6);
            assert!((s.zacc - (-9.7103)).abs() < 1e-5);
            assert_eq!(s.abs_pressure, 1013.25);
        }
        _ => panic!("0: wrong message"),
    }
    match frames[1].decode().unwrap() {
        Message::HilStateQuaternion(q) => {
            assert_eq!(q.time_usec, 1_000_000);
            assert!((q.attitude_quaternion[0] - 0.9998).abs() < 1e-6);
            assert!((q.attitude_quaternion[2] - 0.017).abs() < 1e-6);
            assert_eq!(q.lat, 473977000);
            assert_eq!(q.alt, 500_000);
            assert_eq!(q.vz, -88);
            assert_eq!(q.zacc, -990);
        }
        _ => panic!("1: wrong message"),
    }
    match frames[2].decode().unwrap() {
        Message::HilGps(g) => {
            assert_eq!(g.fix_type, 3);
            assert_eq!(g.lat, 473977011);
            assert_eq!(g.alt, 500_880);
            assert_eq!(g.eph, 100);
            assert_eq!(g.vd, -8);
            assert_eq!(g.cog, 27000);
            assert_eq!(g.yaw, 0); // zero-filled extension
        }
        _ => panic!("2: wrong message"),
    }
    match frames[3].decode().unwrap() {
        Message::HilActuatorControls(a) => {
            assert_eq!(a.time_usec, 1_000_000);
            assert!((a.controls[0] - 0.1).abs() < 1e-6);
            assert!((a.controls[1] - (-0.2)).abs() < 1e-6);
            assert_eq!(a.mode, 1);
            assert_eq!(a.flags, 0);
        }
        _ => panic!("3: wrong message"),
    }
    match frames[4].decode().unwrap() {
        Message::CommandLong(c) => {
            assert_eq!(c.command, 511);
            assert!((c.param1 - 115.0).abs() < 1e-4);
            assert!((c.param2 - 5000.0).abs() < 1e-3);
        }
        _ => panic!("4: wrong message"),
    }
    match frames[5].decode().unwrap() {
        Message::CommandAck(a) => {
            assert_eq!(a.command, 511);
            assert_eq!(a.result, 0);
        }
        _ => panic!("5: wrong message"),
    }
}

/// MAVLink v2 trailing-zero truncation: pymavlink parity. A COMMAND_ACK with
/// result 0 and zero extensions carries a 2-byte payload on the wire; PX4's
/// decoder zero-fills (verified live during bring-up).
#[test]
fn trailing_zero_truncation_matches_pymavlink() {
    // Golden COMMAND_ACK: LEN byte is 2 (see GOLDEN_COMMAND_ACK[1]).
    assert_eq!(GOLDEN_COMMAND_ACK[1], 2);
    let ack = command_ack_msg();
    let payload = Message::CommandAck(ack).pack_payload();
    assert_eq!(payload.len(), 2);
    assert_eq!(&payload[..], &GOLDEN_COMMAND_ACK[10..12]);
}

/// Trailing-zero truncation is applied by the packer, so a HIL_ACTUATOR_CONTROLS
/// with zero flags carries 73 payload bytes on the wire (PX4's decoder
/// zero-fills the trimmed `flags` field).
#[test]
fn payload_lengths_match_px4_headers() {
    assert_eq!(Message::HilSensor(sensor_msg()).pack_payload().len(), 65);
    assert_eq!(Message::HilStateQuaternion(hsq_msg()).pack_payload().len(), 64);
    assert_eq!(Message::HilGps(gps_msg()).pack_payload().len(), 36); // id/yaw zero-trimmed
    assert_eq!(Message::HilActuatorControls(actuator_msg()).pack_payload().len(), 73); // flags zero-trimmed
    assert_eq!(Message::CommandLong(command_long_msg()).pack_payload().len(), 32); // confirmation zero-trimmed
    assert_eq!(Message::CommandAck(command_ack_msg()).pack_payload().len(), 2);
}

/// HIL_ACTUATOR_CONTROLS golden is in the PX4 v1.16.2 wire layout
/// (time, controls@8, mode@72, flags@73). Current common.xml (and therefore
/// pymavlink >= 2.4.x) swapped mode/flags; PX4's pinned dialect is the
/// authority for what we decode — see ADR-006 in docs/adr/.
#[test]
fn hil_actuator_controls_px4_layout_offsets() {
    // Golden wire bytes -> decode.
    let mut p = FrameParser::new();
    p.feed(GOLDEN_HIL_ACTUATOR_CONTROLS);
    let frames = p.take();
    assert_eq!(frames.len(), 1);
    match frames[0].decode().unwrap() {
        Message::HilActuatorControls(a) => {
            assert_eq!(a.time_usec, 1_000_000);
            assert!((a.controls[0] - 0.1).abs() < 1e-6);
            assert!((a.controls[1] - (-0.2)).abs() < 1e-6);
            assert!((a.controls[2] - 0.3).abs() < 1e-6);
            assert!((a.controls[3] - (-0.4)).abs() < 1e-6);
            assert_eq!(a.controls[4], 0.0);
            assert_eq!(a.mode, 1);
            assert_eq!(a.flags, 0);
        }
        _ => panic!("wrong message"),
    }
    // Our encoder is byte-identical to the PX4-layout golden (modulo the
    // trailing-zero trim of the zero `flags` field).
    let msg = Message::HilActuatorControls(actuator_msg());
    let frame = Frame::from_message(&msg, 3, SYS_ID, COMP_ID);
    let bytes = frame.encode();
    assert_eq!(bytes[1], 73);
    assert_eq!(&bytes[10..73], &GOLDEN_HIL_ACTUATOR_CONTROLS[10..73]);
}

/// The frame encoder produces the sequence number it is given; wrap-around
/// at 256 is identity (the transport owns the counter and its wrap).
#[test]
fn seq_counter_semantics() {
    let msg = Message::CommandAck(command_ack_msg());
    let b0 = Frame::from_message(&msg, 0, SYS_ID, COMP_ID).encode();
    let b255 = Frame::from_message(&msg, 255, SYS_ID, COMP_ID).encode();
    assert_eq!(b0[4], 0);
    assert_eq!(b255[4], 255);
    // seq participates in the CRC: different seq -> different frame bytes.
    assert_ne!(b0[4..], b255[4..]);
}
