//! fleet-mavlink — self-contained GCS-side MAVLink v2 codec and per-vehicle
//! UDP link tasks (spec §3).
//!
//! Deliberately dependency-light and **independent of the rustsitsim
//! crates**: the codec here is the GCS-side subset of the protocol with
//! golden vectors generated by pymavlink (see ADR-0001 for the interim
//! cross-repo strategy).

pub mod crc;
pub mod frame;
pub mod messages;
pub mod link;

pub use frame::{crc_extra, Decoder, Frame};
pub use link::{
    spawn_link, CmdAck, LinkCommand, LinkConfig, LinkHandle, LinkShared, LinkStats,
    MissionDownloadResult, MissionUploadResult, ParamDownloadState, ParamEntry, ParamStore,
    ParamVal, SetpointGoal, SetpointSlot,
};
pub use messages::{
    decode_event, cmds, enums, ids, Attitude, BatteryStatus, CommandAck, CommandLong,
    GlobalPositionInt, Heartbeat, HomePosition, LocalPositionNed, MissionItemInt,
    ParamRequestList, ParamRequestRead, ParamSet, ParamValue, Ping, SetPositionTargetLocalNed,
    StatusText, SysStatus, TelemetryEvent,
};
