//! The fleet's MAVLink message subset: strongly-typed payloads with pack and
//! unpack, in the **wire field order** used by PX4's generated C headers and
//! pymavlink (the official generator sorts non-extension fields by size,
//! largest first, and keeps extension fields at the tail).
//!
//! Layout provenance: cross-checked between
//! `PX4-Autopilot/build/px4_sitl_default/mavlink/common/mavlink_msg_*.h`
//! (what PX4 emits/expects) and pymavlink 2.4.49 v2.0 common dialect
//! `ordered_fieldnames`; golden vectors in `tests/golden_mavlink.json` were
//! generated by pymavlink itself and pin the byte-level contract.

#![forbid(unsafe_code)]

pub mod ids {
    pub const HEARTBEAT: u32 = 0;
    pub const SYS_STATUS: u32 = 1;
    pub const PING: u32 = 4;
    pub const ATTITUDE: u32 = 30;
    pub const LOCAL_POSITION_NED: u32 = 32;
    pub const GLOBAL_POSITION_INT: u32 = 33;
    pub const COMMAND_LONG: u32 = 76;
    pub const COMMAND_ACK: u32 = 77;
    pub const SET_POSITION_TARGET_LOCAL_NED: u32 = 84;
    pub const BATTERY_STATUS: u32 = 147;
    pub const HOME_POSITION: u32 = 242;
    pub const STATUSTEXT: u32 = 253;
    pub const PARAM_SET: u32 = 23;
    pub const PARAM_VALUE: u32 = 22;
    /// PARAM_REQUEST_READ (20): read one parameter (by id or index).
    pub const PARAM_REQUEST_READ: u32 = 20;
    /// PARAM_REQUEST_LIST (21): request the full parameter dump — the
    /// QGroundControl-style initial parameter download.
    pub const PARAM_REQUEST_LIST: u32 = 21;
}

pub mod cmds {
    pub const NAV_TAKEOFF: u16 = 22;
    pub const NAV_LAND: u16 = 21;
    pub const NAV_RETURN_TO_LAUNCH: u16 = 20;
    pub const COMPONENT_ARM_DISARM: u16 = 400;
    pub const DO_SET_MODE: u16 = 176;
    pub const SET_MESSAGE_INTERVAL: u16 = 511;
    /// MAV_CMD_PREFLIGHT_CALIBRATION (241): sensor calibration triggers
    /// (accel/gyro/mag/level-horizon/airspeed), param-matrix semantics.
    pub const PREFLIGHT_CALIBRATION: u16 = 241;
    /// MAV_CMD_PREFLIGHT_RESTART_SHUTDOWN (246): param1=1 restarts the
    /// autopilot (airframe changes apply at next boot).
    pub const PREFLIGHT_RESTART_SHUTDOWN: u16 = 246;
}

pub mod enums {
    pub const MAV_TYPE_GCS: u8 = 6;
    pub const MAV_AUTOPILOT_INVALID: u8 = 8;
    pub const MAV_AUTOPILOT_PX4: u8 = 12;
    pub const MAV_STATE_ACTIVE: u8 = 4;
    pub const MAV_MODE_FLAG_CUSTOM_ENABLED: u8 = 1;
    pub const MAV_MODE_FLAG_SAFETY_ARMED: u8 = 128;
    pub const MAV_FRAME_LOCAL_NED: u8 = 1;
    pub const MAV_RESULT_ACCEPTED: u8 = 0;
    pub const MAV_RESULT_TEMPORARILY_REJECTED: u8 = 1;
    pub const MAV_RESULT_DENIED: u8 = 2;
    pub const MAV_RESULT_UNSUPPORTED: u8 = 3;
    pub const MAV_RESULT_FAILED: u8 = 4;
    pub const MAV_RESULT_IN_PROGRESS: u8 = 5;
}

// ---------------------------------------------------------------------------
// Message structs (pack = GCS->vehicle or vehicle->GCS as applicable)
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq)]
pub struct Heartbeat {
    pub custom_mode: u32,
    pub mavtype: u8,
    pub autopilot: u8,
    pub base_mode: u8,
    pub system_status: u8,
    pub mavlink_version: u8,
}

impl Heartbeat {
    pub fn pack(&self) -> Vec<u8> {
        let mut v = Vec::with_capacity(9);
        v.extend_from_slice(&self.custom_mode.to_le_bytes());
        v.push(self.mavtype);
        v.push(self.autopilot);
        v.push(self.base_mode);
        v.push(self.system_status);
        v.push(self.mavlink_version);
        v
    }
    pub fn unpack(p: &[u8]) -> Option<Self> {
        let p = padded(p, 9);
        Some(Heartbeat {
            custom_mode: u32::from_le_bytes(p[0..4].try_into().ok()?),
            mavtype: p[4],
            autopilot: p[5],
            base_mode: p[6],
            system_status: p[7],
            mavlink_version: p[8],
        })
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct CommandLong {
    pub target_system: u8,
    pub target_component: u8,
    pub command: u16,
    pub confirmation: u8,
    pub params: [f32; 7],
}

impl CommandLong {
    pub fn pack(&self) -> Vec<u8> {
        let mut v = Vec::with_capacity(33);
        for p in &self.params {
            v.extend_from_slice(&p.to_le_bytes());
        }
        v.extend_from_slice(&self.command.to_le_bytes());
        v.push(self.target_system);
        v.push(self.target_component);
        v.push(self.confirmation);
        v
    }
    pub fn unpack(p: &[u8]) -> Option<Self> {
        let p = padded(p, 33);
        let mut params = [0f32; 7];
        for (i, item) in params.iter_mut().enumerate() {
            *item = f32::from_le_bytes(p[i * 4..i * 4 + 4].try_into().ok()?);
        }
        Some(CommandLong {
            target_system: *p.get(30)?,
            target_component: *p.get(31)?,
            command: u16::from_le_bytes(p[28..30].try_into().ok()?),
            confirmation: p.get(32).copied().unwrap_or(0),
            params,
        })
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct CommandAck {
    pub command: u16,
    pub result: u8,
    pub progress: u8,
    pub result_param2: i32,
    pub target_system: u8,
    pub target_component: u8,
}

impl CommandAck {
    pub fn pack(&self) -> Vec<u8> {
        let mut v = Vec::with_capacity(9);
        v.extend_from_slice(&self.command.to_le_bytes());
        v.push(self.result);
        v.push(self.progress);
        v.extend_from_slice(&self.result_param2.to_le_bytes());
        v.push(self.target_system);
        v.push(self.target_component);
        v
    }
    pub fn unpack(p: &[u8]) -> Option<Self> {
        if p.len() < 3 {
            return None;
        }
        Some(CommandAck {
            command: u16::from_le_bytes(p[0..2].try_into().ok()?),
            result: p[2],
            progress: p.get(3).copied().unwrap_or(255),
            result_param2: if p.len() >= 8 {
                i32::from_le_bytes(p[4..8].try_into().ok()?)
            } else {
                0
            },
            target_system: p.get(8).copied().unwrap_or(0),
            target_component: p.get(9).copied().unwrap_or(0),
        })
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct SetPositionTargetLocalNed {
    pub time_boot_ms: u32,
    pub target_system: u8,
    pub target_component: u8,
    pub coordinate_frame: u8,
    pub type_mask: u16,
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub vx: f32,
    pub vy: f32,
    pub vz: f32,
    pub afx: f32,
    pub afy: f32,
    pub afz: f32,
    pub yaw: f32,
    pub yaw_rate: f32,
}

impl Default for SetPositionTargetLocalNed {
    fn default() -> Self {
        Self {
            time_boot_ms: 0,
            target_system: 1,
            target_component: 1,
            coordinate_frame: enums::MAV_FRAME_LOCAL_NED,
            type_mask: 0,
            x: 0.0,
            y: 0.0,
            z: 0.0,
            vx: 0.0,
            vy: 0.0,
            vz: 0.0,
            afx: 0.0,
            afy: 0.0,
            afz: 0.0,
            yaw: 0.0,
            yaw_rate: 0.0,
        }
    }
}

impl SetPositionTargetLocalNed {
    pub fn pack(&self) -> Vec<u8> {
        let mut v = Vec::with_capacity(53);
        v.extend_from_slice(&self.time_boot_ms.to_le_bytes());
        for f in [self.x, self.y, self.z, self.vx, self.vy, self.vz, self.afx, self.afy, self.afz, self.yaw, self.yaw_rate] {
            v.extend_from_slice(&f.to_le_bytes());
        }
        v.extend_from_slice(&self.type_mask.to_le_bytes());
        v.push(self.target_system);
        v.push(self.target_component);
        v.push(self.coordinate_frame);
        v
    }
    pub fn unpack(p: &[u8]) -> Option<Self> {
        let p = padded(p, 53);
        let mut m = Self::default();
        m.time_boot_ms = u32::from_le_bytes(p[0..4].try_into().ok()?);
        let mut fs = [
            &mut m.x, &mut m.y, &mut m.z, &mut m.vx, &mut m.vy, &mut m.vz, &mut m.afx, &mut m.afy, &mut m.afz,
            &mut m.yaw, &mut m.yaw_rate,
        ];
        for (i, item) in fs.iter_mut().enumerate() {
            **item = f32::from_le_bytes(p[4 + i * 4..8 + i * 4].try_into().ok()?);
        }
        m.type_mask = u16::from_le_bytes(p[48..50].try_into().ok()?);
        m.target_system = p.get(50).copied().unwrap_or(0);
        m.target_component = p.get(51).copied().unwrap_or(0);
        m.coordinate_frame = p.get(52).copied().unwrap_or(0);
        Some(m)
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct Attitude {
    pub time_boot_ms: u32,
    pub roll: f32,
    pub pitch: f32,
    pub yaw: f32,
    pub rollspeed: f32,
    pub pitchspeed: f32,
    pub yawspeed: f32,
}

impl Attitude {
    pub fn pack(&self) -> Vec<u8> {
        pack_f32s_prefix_u32(self.time_boot_ms, &[
            self.roll, self.pitch, self.yaw, self.rollspeed, self.pitchspeed, self.yawspeed,
        ])
    }
    pub fn unpack(p: &[u8]) -> Option<Self> {
        let p = padded(p, 28);
        let f = read_f32s(&p[4..28], 6)?;
        Some(Attitude {
            time_boot_ms: u32::from_le_bytes(p[0..4].try_into().ok()?),
            roll: f[0],
            pitch: f[1],
            yaw: f[2],
            rollspeed: f[3],
            pitchspeed: f[4],
            yawspeed: f[5],
        })
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct LocalPositionNed {
    pub time_boot_ms: u32,
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub vx: f32,
    pub vy: f32,
    pub vz: f32,
}

impl LocalPositionNed {
    pub fn pack(&self) -> Vec<u8> {
        pack_f32s_prefix_u32(self.time_boot_ms, &[self.x, self.y, self.z, self.vx, self.vy, self.vz])
    }
    pub fn unpack(p: &[u8]) -> Option<Self> {
        let p = padded(p, 28);
        let f = read_f32s(&p[4..28], 6)?;
        Some(LocalPositionNed {
            time_boot_ms: u32::from_le_bytes(p[0..4].try_into().ok()?),
            x: f[0],
            y: f[1],
            z: f[2],
            vx: f[3],
            vy: f[4],
            vz: f[5],
        })
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct GlobalPositionInt {
    pub time_boot_ms: u32,
    pub lat: i32,
    pub lon: i32,
    pub alt: i32,
    pub relative_alt: i32,
    pub vx: i16,
    pub vy: i16,
    pub vz: i16,
    pub hdg: u16,
}

impl GlobalPositionInt {
    pub fn pack(&self) -> Vec<u8> {
        let mut v = Vec::with_capacity(28);
        v.extend_from_slice(&self.time_boot_ms.to_le_bytes());
        v.extend_from_slice(&self.lat.to_le_bytes());
        v.extend_from_slice(&self.lon.to_le_bytes());
        v.extend_from_slice(&self.alt.to_le_bytes());
        v.extend_from_slice(&self.relative_alt.to_le_bytes());
        v.extend_from_slice(&self.vx.to_le_bytes());
        v.extend_from_slice(&self.vy.to_le_bytes());
        v.extend_from_slice(&self.vz.to_le_bytes());
        v.extend_from_slice(&self.hdg.to_le_bytes());
        v
    }
    pub fn unpack(p: &[u8]) -> Option<Self> {
        let p = padded(p, 28);
        Some(GlobalPositionInt {
            time_boot_ms: u32::from_le_bytes(p[0..4].try_into().ok()?),
            lat: i32::from_le_bytes(p[4..8].try_into().ok()?),
            lon: i32::from_le_bytes(p[8..12].try_into().ok()?),
            alt: i32::from_le_bytes(p[12..16].try_into().ok()?),
            relative_alt: i32::from_le_bytes(p[16..20].try_into().ok()?),
            vx: i16::from_le_bytes(p[20..22].try_into().ok()?),
            vy: i16::from_le_bytes(p[22..24].try_into().ok()?),
            vz: i16::from_le_bytes(p[24..26].try_into().ok()?),
            hdg: u16::from_le_bytes(p[26..28].try_into().ok()?),
        })
    }
}

/// The subset of SYS_STATUS the fleet consumes.
#[derive(Debug, Clone, PartialEq)]
pub struct SysStatus {
    pub load: u16,
    pub voltage_battery_mv: u16,
    pub current_battery_ca: i16,
    pub battery_remaining_pct: i8,
}

impl SysStatus {
    pub fn pack(&self) -> Vec<u8> {
        let mut v = vec![0u8; 31];
        v[12..14].copy_from_slice(&self.load.to_le_bytes());
        v[14..16].copy_from_slice(&self.voltage_battery_mv.to_le_bytes());
        v[16..18].copy_from_slice(&self.current_battery_ca.to_le_bytes());
        v[30] = self.battery_remaining_pct as u8;
        v
    }
    pub fn unpack(p: &[u8]) -> Option<Self> {
        let p = padded(p, 31);
        Some(SysStatus {
            load: u16::from_le_bytes(p[12..14].try_into().ok()?),
            voltage_battery_mv: u16::from_le_bytes(p[14..16].try_into().ok()?),
            current_battery_ca: i16::from_le_bytes(p[16..18].try_into().ok()?),
            battery_remaining_pct: p[30] as i8,
        })
    }
}

/// The subset of BATTERY_STATUS the fleet consumes (cell 0 voltage).
#[derive(Debug, Clone, PartialEq)]
pub struct BatteryStatus {
    pub voltages_mv: [u16; 10],
    pub current_battery_ca: i16,
    pub id: u8,
    pub battery_remaining_pct: i8,
    pub temperature_cdegc: i16,
}

impl BatteryStatus {
    pub fn pack(&self) -> Vec<u8> {
        // current_consumed(i32) energy_consumed(i32) temperature(i16)
        // voltages[10](u16) current_battery(i16) id func type remaining(i8)
        let mut v = Vec::with_capacity(55);
        v.extend_from_slice(&0i32.to_le_bytes());
        v.extend_from_slice(&0i32.to_le_bytes());
        v.extend_from_slice(&self.temperature_cdegc.to_le_bytes());
        for u in self.voltages_mv {
            v.extend_from_slice(&u.to_le_bytes());
        }
        v.extend_from_slice(&self.current_battery_ca.to_le_bytes());
        v.push(self.id);
        v.push(0);
        v.push(0);
        v.push(self.battery_remaining_pct as u8);
        v
    }
    pub fn unpack(p: &[u8]) -> Option<Self> {
        let p = padded(p, 36);
        let mut voltages_mv = [0u16; 10];
        for (i, item) in voltages_mv.iter_mut().enumerate() {
            let off = 10 + i * 2;
            *item = u16::from_le_bytes(p[off..off + 2].try_into().ok()?);
        }
        Some(BatteryStatus {
            voltages_mv,
            current_battery_ca: i16::from_le_bytes(p[30..32].try_into().ok()?),
            id: p[32],
            battery_remaining_pct: p[35] as i8,
            temperature_cdegc: i16::from_le_bytes(p[8..10].try_into().ok()?),
        })
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct StatusText {
    pub severity: u8,
    pub text: String,
    pub id: u8,
    pub chunk_seq: u8,
}

impl StatusText {
    pub fn pack(&self) -> Vec<u8> {
        let mut v = Vec::with_capacity(53);
        v.push(self.severity);
        let mut text = [0u8; 50];
        for (i, b) in self.text.bytes().take(50).enumerate() {
            text[i] = b;
        }
        v.extend_from_slice(&text);
        v.push(self.id);
        v.push(self.chunk_seq);
        v
    }
    pub fn unpack(p: &[u8]) -> Option<Self> {
        if p.len() < 2 {
            return None;
        }
        let text_end = p.len().min(51);
        let raw = &p[1..text_end];
        let text = String::from_utf8_lossy(raw)
            .trim_end_matches('\0')
            .to_string();
        Some(StatusText {
            severity: p[0],
            text,
            id: p.get(51).copied().unwrap_or(0),
            chunk_seq: p.get(52).copied().unwrap_or(0),
        })
    }
}

/// The subset of HOME_POSITION the fleet consumes (local NED anchor).
#[derive(Debug, Clone, PartialEq)]
pub struct HomePosition {
    pub latitude: i32,
    pub longitude: i32,
    pub altitude: i32,
    pub x: f32,
    pub y: f32,
    pub z: f32,
}

impl HomePosition {
    pub fn pack(&self) -> Vec<u8> {
        let mut v = Vec::with_capacity(60);
        v.extend_from_slice(&self.latitude.to_le_bytes());
        v.extend_from_slice(&self.longitude.to_le_bytes());
        v.extend_from_slice(&self.altitude.to_le_bytes());
        for f in [self.x, self.y, self.z] {
            v.extend_from_slice(&f.to_le_bytes());
        }
        v.extend_from_slice(&[0u8; 28]); // q[4] + approach[3]
        v
    }
    pub fn unpack(p: &[u8]) -> Option<Self> {
        let p = padded(p, 24);
        Some(HomePosition {
            latitude: i32::from_le_bytes(p[0..4].try_into().ok()?),
            longitude: i32::from_le_bytes(p[4..8].try_into().ok()?),
            altitude: i32::from_le_bytes(p[8..12].try_into().ok()?),
            x: f32::from_le_bytes(p[12..16].try_into().ok()?),
            y: f32::from_le_bytes(p[16..20].try_into().ok()?),
            z: f32::from_le_bytes(p[20..24].try_into().ok()?),
        })
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct Ping {
    pub time_usec: u64,
    pub seq: u32,
    pub target_system: u8,
    pub target_component: u8,
}

impl Ping {
    pub fn pack(&self) -> Vec<u8> {
        let mut v = Vec::with_capacity(16);
        v.extend_from_slice(&self.time_usec.to_le_bytes());
        v.extend_from_slice(&self.seq.to_le_bytes());
        v.push(self.target_system);
        v.push(self.target_component);
        v
    }
    pub fn unpack(p: &[u8]) -> Option<Self> {
        let p = padded(p, 14);
        Some(Ping {
            time_usec: u64::from_le_bytes(p[0..8].try_into().ok()?),
            seq: u32::from_le_bytes(p[8..12].try_into().ok()?),
            target_system: p[12],
            target_component: p[13],
        })
    }
}

// ---------------------------------------------------------------------------
// High-level decoded enum published by the link task
// ---------------------------------------------------------------------------

/// One decoded inbound message, published to the aggregator.
#[derive(Debug, Clone, PartialEq)]
pub enum TelemetryEvent {
    ParamValue {
        param_id: String,
        value: f32,
        param_type: u8,
        /// Total parameter count reported by the vehicle (download progress).
        param_count: u16,
        /// This parameter's index in the vehicle's parameter table.
        param_index: u16,
    },
    Heartbeat {
        sysid: u8,
        compid: u8,
        base_mode: u8,
        custom_mode: u32,
    },
    Attitude {
        time_boot_ms: u32,
        roll: f32,
        pitch: f32,
        yaw: f32,
    },
    LocalPositionNed {
        time_boot_ms: u32,
        x: f32,
        y: f32,
        z: f32,
        vx: f32,
        vy: f32,
        vz: f32,
    },
    GlobalPositionInt {
        lat: i32,
        lon: i32,
        alt: i32,
        relative_alt: i32,
    },
    SysStatus {
        battery_remaining_pct: i8,
        voltage_battery_mv: u16,
        current_battery_ca: i16,
    },
    BatteryStatus {
        battery_remaining_pct: i8,
        voltage_mv: u16,
        current_battery_ca: i16,
    },
    HomePosition {
        x: f32,
        y: f32,
        z: f32,
        lat: i32,
        lon: i32,
        alt: i32,
    },
    StatusText {
        severity: u8,
        text: String,
    },
    CommandAck {
        command: u16,
        result: u8,
        progress: u8,
        target_system: u8,
        target_component: u8,
    },
    Ping {
        time_usec: u64,
        seq: u32,
    },
    /// Structurally valid frame with no decoder in the fleet subset.
    Unknown {
        msgid: u32,
        len: usize,
    },
}

/// Decode a frame's payload into a `TelemetryEvent`.
pub fn decode_event(frame: &crate::frame::Frame) -> Option<TelemetryEvent> {
    let p = &frame.payload[..];
    Some(match frame.msgid {
        ids::HEARTBEAT => {
            let m = Heartbeat::unpack(p)?;
            TelemetryEvent::Heartbeat {
                sysid: frame.sysid,
                compid: frame.compid,
                base_mode: m.base_mode,
                custom_mode: m.custom_mode,
            }
        }
        ids::PARAM_VALUE => {
            let m = ParamValue::unpack(p)?;
            TelemetryEvent::ParamValue {
                param_id: m.param_id_string(),
                value: m.param_value,
                param_type: m.param_type,
                param_count: m.param_count,
                param_index: m.param_index,
            }
        }
        ids::ATTITUDE => {
            let m = Attitude::unpack(p)?;
            TelemetryEvent::Attitude {
                time_boot_ms: m.time_boot_ms,
                roll: m.roll,
                pitch: m.pitch,
                yaw: m.yaw,
            }
        }
        ids::LOCAL_POSITION_NED => {
            let m = LocalPositionNed::unpack(p)?;
            TelemetryEvent::LocalPositionNed {
                time_boot_ms: m.time_boot_ms,
                x: m.x,
                y: m.y,
                z: m.z,
                vx: m.vx,
                vy: m.vy,
                vz: m.vz,
            }
        }
        ids::GLOBAL_POSITION_INT => {
            let m = GlobalPositionInt::unpack(p)?;
            TelemetryEvent::GlobalPositionInt {
                lat: m.lat,
                lon: m.lon,
                alt: m.alt,
                relative_alt: m.relative_alt,
            }
        }
        ids::SYS_STATUS => {
            let m = SysStatus::unpack(p)?;
            TelemetryEvent::SysStatus {
                battery_remaining_pct: m.battery_remaining_pct,
                voltage_battery_mv: m.voltage_battery_mv,
                current_battery_ca: m.current_battery_ca,
            }
        }
        ids::BATTERY_STATUS => {
            let m = BatteryStatus::unpack(p)?;
            TelemetryEvent::BatteryStatus {
                battery_remaining_pct: m.battery_remaining_pct,
                voltage_mv: m.voltages_mv[0],
                current_battery_ca: m.current_battery_ca,
            }
        }
        ids::HOME_POSITION => {
            let m = HomePosition::unpack(p)?;
            TelemetryEvent::HomePosition {
                x: m.x,
                y: m.y,
                z: m.z,
                lat: m.latitude,
                lon: m.longitude,
                alt: m.altitude,
            }
        }
        ids::STATUSTEXT => {
            let m = StatusText::unpack(p)?;
            TelemetryEvent::StatusText {
                severity: m.severity,
                text: m.text,
            }
        }
        ids::COMMAND_ACK => {
            let m = CommandAck::unpack(p)?;
            TelemetryEvent::CommandAck {
                command: m.command,
                result: m.result,
                progress: m.progress,
                target_system: m.target_system,
                target_component: m.target_component,
            }
        }
        ids::PING => {
            let m = Ping::unpack(p)?;
            TelemetryEvent::Ping {
                time_usec: m.time_usec,
                seq: m.seq,
            }
        }
        other => TelemetryEvent::Unknown {
            msgid: other,
            len: p.len(),
        },
    })
}


/// MAVLink v2 trailing-zero trimming: a short payload means the trimmed
/// fields were zero. Pad to the full length before positional reads.
/// PARAM_SET (23): manager → PX4 parameter write (v0.1: REAL32 only).
#[derive(Debug, Clone, PartialEq)]
pub struct ParamSet {
    pub target_system: u8,
    pub target_component: u8,
    pub param_id: [u8; 16],
    pub param_value: f32,
    /// MAV_PARAM_TYPE_REAL32 = 9.
    pub param_type: u8,
}

impl ParamSet {
    /// Build from a &str id (NUL-padded, truncated at 15 bytes).
    pub fn from_str(param_id: &str, value: f32, target_system: u8, target_component: u8) -> Self {
        let mut id = [0u8; 16];
        for (i, b) in param_id.as_bytes().iter().take(15).enumerate() {
            id[i] = *b;
        }
        ParamSet {
            target_system,
            target_component,
            param_id: id,
            param_value: value,
            param_type: 9,
        }
    }

    pub fn pack(&self) -> Vec<u8> {
        // Wire order (PX4-generated header / pymavlink 2.4.49, golden-pinned):
        // param_value(f32) @0, target_system @4, target_component @5,
        // param_id[16] @6, param_type @22.
        let mut v = Vec::with_capacity(23);
        v.extend_from_slice(&self.param_value.to_le_bytes());
        v.push(self.target_system);
        v.push(self.target_component);
        v.extend_from_slice(&self.param_id);
        v.push(self.param_type);
        v
    }
}

/// PARAM_VALUE (22): PX4's confirmation echo for parameter writes.
#[derive(Debug, Clone, PartialEq)]
pub struct ParamValue {
    pub param_id: [u8; 16],
    pub param_value: f32,
    pub param_type: u8,
    pub param_count: u16,
    pub param_index: u16,
}

impl ParamValue {
    pub fn unpack(p: &[u8]) -> Option<Self> {
        // Wire order (PX4-generated header / pymavlink 2.4.49, golden-pinned):
        // param_value(f32) @0, param_count @4, param_index @6,
        // param_id[16] @8, param_type @24. The original v0.1 decoder read the
        // XML declaration order instead, so every live PARAM_VALUE echo
        // decoded to a garbage id and param writes never confirmed — fixed
        // with ADR-0016 and pinned by the PARAM_VALUE_echo golden vector.
        let p = padded(p, 25);
        Some(ParamValue {
            param_value: f32::from_le_bytes(p[0..4].try_into().ok()?),
            param_count: u16::from_le_bytes(p[4..6].try_into().ok()?),
            param_index: u16::from_le_bytes(p[6..8].try_into().ok()?),
            param_id: p[8..24].try_into().ok()?,
            param_type: p[24],
        })
    }

    /// The id as a NUL-terminated string.
    pub fn param_id_string(&self) -> String {
        param_id_to_string(&self.param_id)
    }
}

/// Decode a MAVLink char[16] parameter id (NUL-padded).
pub fn param_id_to_string(id: &[u8; 16]) -> String {
    let end = id.iter().position(|&b| b == 0).unwrap_or(16);
    String::from_utf8_lossy(&id[..end]).into_owned()
}

/// PARAM_REQUEST_LIST (21): request the vehicle's full parameter dump. This
/// is exactly the initial parameter download QGroundControl/Mission Planner
/// perform on connect: the vehicle answers with a burst of PARAM_VALUE frames
/// carrying `param_count`/`param_index` progress fields.
///
/// Wire order (generated header field order, largest-first): two u8 targets
/// only — 2-byte payload.
#[derive(Debug, Clone, PartialEq)]
pub struct ParamRequestList {
    pub target_system: u8,
    pub target_component: u8,
}

impl ParamRequestList {
    pub fn pack(&self) -> Vec<u8> {
        vec![self.target_system, self.target_component]
    }

    pub fn unpack(p: &[u8]) -> Option<Self> {
        if p.len() < 2 {
            return None;
        }
        Some(ParamRequestList {
            target_system: p[0],
            target_component: p[1],
        })
    }
}

/// PARAM_REQUEST_READ (20): read a single parameter. `param_index = -1` plus
/// a non-empty `param_id` requests by id; otherwise the index selects.
///
/// Wire order (PX4-generated header / pymavlink 2.4.49, golden-pinned):
/// `param_index` (i16) @0, `target_system` @2, `target_component` @3,
/// `param_id` char[16] @4 — 20-byte payload.
#[derive(Debug, Clone, PartialEq)]
pub struct ParamRequestRead {
    pub param_id: [u8; 16],
    pub param_index: i16,
    pub target_system: u8,
    pub target_component: u8,
}

impl ParamRequestRead {
    /// Request by id (index = -1).
    pub fn from_str(param_id: &str, target_system: u8, target_component: u8) -> Self {
        let mut id = [0u8; 16];
        for (i, b) in param_id.as_bytes().iter().take(15).enumerate() {
            id[i] = *b;
        }
        ParamRequestRead {
            param_id: id,
            param_index: -1,
            target_system,
            target_component,
        }
    }

    pub fn pack(&self) -> Vec<u8> {
        // Wire order (PX4-generated header / pymavlink 2.4.49, golden-pinned):
        // param_index(i16) @0, target_system @2, target_component @3,
        // param_id[16] @4.
        let mut v = Vec::with_capacity(20);
        v.extend_from_slice(&self.param_index.to_le_bytes());
        v.push(self.target_system);
        v.push(self.target_component);
        v.extend_from_slice(&self.param_id);
        v
    }

    pub fn unpack(p: &[u8]) -> Option<Self> {
        let p = padded(p, 20);
        Some(ParamRequestRead {
            param_index: i16::from_le_bytes(p[0..2].try_into().ok()?),
            target_system: p[2],
            target_component: p[3],
            param_id: p[4..20].try_into().ok()?,
        })
    }

    /// The id as a NUL-terminated string.
    pub fn param_id_string(&self) -> String {
        param_id_to_string(&self.param_id)
    }
}

fn padded(p: &[u8], n: usize) -> Vec<u8> {
    let mut v = Vec::with_capacity(n);
    v.extend_from_slice(p);
    v.resize(n, 0);
    v
}

fn pack_f32s_prefix_u32(prefix: u32, fs: &[f32]) -> Vec<u8> {
    let mut v = Vec::with_capacity(4 + fs.len() * 4);
    v.extend_from_slice(&prefix.to_le_bytes());
    for f in fs {
        v.extend_from_slice(&f.to_le_bytes());
    }
    v
}

fn read_f32s(p: &[u8], n: usize) -> Option<Vec<f32>> {
    if p.len() < n * 4 {
        return None;
    }
    (0..n)
        .map(|i| {
            let b: [u8; 4] = p[i * 4..i * 4 + 4].try_into().ok()?;
            Some(f32::from_le_bytes(b))
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn command_long_pack_order() {
        let c = CommandLong {
            target_system: 1,
            target_component: 1,
            command: 400,
            confirmation: 0,
            params: [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
        };
        let p = c.pack();
        // params first, then command, targets, confirmation
        assert_eq!(p[0..4], 1.0f32.to_le_bytes());
        assert_eq!(&p[28..30], &400u16.to_le_bytes());
        assert_eq!(p[30], 1);
        assert_eq!(p[31], 1);
        assert_eq!(p.len(), 33);
    }

    #[test]
    fn heartbeat_pack_order() {
        let h = Heartbeat {
            custom_mode: 0x40300,
            mavtype: 2,
            autopilot: 12,
            base_mode: 209,
            system_status: 4,
            mavlink_version: 3,
        };
        let p = h.pack();
        assert_eq!(&p[0..4], &0x40300u32.to_le_bytes());
        assert_eq!(p[4], 2);
        assert_eq!(p[5], 12);
        assert_eq!(p[6], 209);
        assert_eq!(p[7], 4);
        assert_eq!(p[8], 3);
    }

    #[test]
    fn setpoint_pack_order() {
        let s = SetPositionTargetLocalNed {
            time_boot_ms: 99,
            x: 1.0,
            y: 2.0,
            z: 3.0,
            type_mask: 2552,
            target_system: 1,
            target_component: 1,
            coordinate_frame: 1,
            ..Default::default()
        };
        let p = s.pack();
        assert_eq!(p.len(), 53);
        assert_eq!(&p[0..4], &99u32.to_le_bytes());
        assert_eq!(&p[4..8], &1.0f32.to_le_bytes());
        assert_eq!(&p[48..50], &2552u16.to_le_bytes());
        assert_eq!(p[50], 1);
        assert_eq!(p[51], 1);
        assert_eq!(p[52], 1);
        let rt = SetPositionTargetLocalNed::unpack(&p).unwrap();
        assert_eq!(rt, s);
    }

    #[test]
    fn param_set_pack_and_value_roundtrip() {
        let s = ParamSet::from_str("NAV_DLL_ACT", 0.0, 1, 1);
        let p = s.pack();
        assert_eq!(p.len(), 23);
        // value first, then targets, then id, then type
        assert_eq!(&p[0..4], &0.0f32.to_le_bytes());
        assert_eq!(p[4], 1);
        assert_eq!(p[5], 1);
        assert_eq!(&p[6..17], b"NAV_DLL_ACT");
        assert_eq!(p[22], 9);
        // PARAM_VALUE echo with the same id: value@0, count@4, index@6,
        // id@8, type@24 — a mid-download-shaped echo (count 722, index 101)
        // so offset errors cannot pass.
        let mut v = vec![0u8; 25];
        v[0..4].copy_from_slice(&0.0f32.to_le_bytes());
        v[4..6].copy_from_slice(&722u16.to_le_bytes());
        v[6..8].copy_from_slice(&101u16.to_le_bytes());
        v[8..19].copy_from_slice(b"NAV_DLL_ACT");
        v[24] = 9;
        let pv = ParamValue::unpack(&v).unwrap();
        assert_eq!(pv.param_id_string(), "NAV_DLL_ACT");
        assert_eq!(pv.param_value, 0.0);
        assert_eq!(pv.param_type, 9);
        assert_eq!(pv.param_count, 722);
        assert_eq!(pv.param_index, 101);
    }

    #[test]
    fn short_payloads_decode_with_defaults() {
        // v2 trailing-zero trimming: COMMAND_ACK with only command+result
        let a = CommandAck::unpack(&[176u8, 0, 0]).unwrap();
        assert_eq!(a.command, 176);
        assert_eq!(a.result, 0);
        assert_eq!(a.progress, 255); // unknown
        assert_eq!(a.target_system, 0);
    }

    /// PARAM_REQUEST_LIST payload is exactly the two target bytes (wire
    /// order from the generated header: target_system, target_component).
    #[test]
    fn param_request_list_pack_order() {
        let p = ParamRequestList {
            target_system: 1,
            target_component: 1,
        }
        .pack();
        assert_eq!(p, vec![1u8, 1u8]);
        assert_eq!(p.len(), 2);
    }

    /// PARAM_REQUEST_READ wire order: i16 index first, then targets, then
    /// char[16] id (PX4 generated header + pymavlink 2.4.49, golden-pinned).
    #[test]
    fn param_request_read_pack_order() {
        let r = ParamRequestRead::from_str("BAT_N_CELLS", 1, 1);
        let p = r.pack();
        assert_eq!(p.len(), 20);
        assert_eq!(p[0..2], (-1i16).to_le_bytes());
        assert_eq!(p[2], 1);
        assert_eq!(p[3], 1);
        assert_eq!(&p[4..15], b"BAT_N_CELLS");
    }

    /// param_id truncation is at 15 bytes (16th byte stays NUL so the
    /// receiver's C-string decode terminates).
    #[test]
    fn param_request_read_id_truncates_at_15() {
        let long_id = "A".repeat(20);
        let r = ParamRequestRead::from_str(&long_id, 1, 1);
        assert_eq!(r.param_id[15], 0);
        assert!(r.param_id.iter().take(15).all(|&b| b == b'A'));
    }
}
