//! PX4 airframe catalog (auto-generated — do not edit by hand).
//!
//! Generated by `fleet/scripts/gen_airframes.py` from the **built**
//! PX4-Autopilot v1.16.2 ROMFS (the union of `etc/init.d/airframes` and
//! `etc/init.d-posix/airframes` — exactly the set PX4's rc.autostart can
//! resolve, so every entry is a SYS_AUTOSTART value this stack can really
//! apply). Names/types/classes come from the airframes' own `@name`,
//! `@type`, `@class` metadata tags — the same tags QGroundControl's airframe
//! browser serves.
//!
//! Regenerate after a PX4 version bump:
//!   python3 fleet/scripts/gen_airframes.py <px4>/build/px4_sitl_default/etc

#![allow(clippy::all)]

/// QGC-style grouping for the console's airframe picker.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AirframeCategory {
    Copter,
    Plane,
    Vtol,
    Rover,
    Boat,
    Underwater,
    Other,
    Simulator,
}

impl AirframeCategory {
    /// Console-facing label (UAV/UGV/USV annotated, QGC browser order).
    pub fn label(self) -> &'static str {
        match self {
            AirframeCategory::Copter => "Multirotor (UAV)",
            AirframeCategory::Plane => "Fixed Wing (UAV)",
            AirframeCategory::Vtol => "VTOL (UAV)",
            AirframeCategory::Rover => "Rover (UGV)",
            AirframeCategory::Boat => "Boat (USV)",
            AirframeCategory::Underwater => "Underwater (UUV)",
            AirframeCategory::Other => "Other",
            AirframeCategory::Simulator => "Simulator (SITL models)",
        }
    }
}

/// One selectable airframe.
#[derive(Debug, Clone, Copy)]
pub struct Airframe {
    /// SYS_AUTOSTART value that selects this airframe at boot.
    pub id: u32,
    /// `@name` from the airframe script.
    pub name: &'static str,
    /// `@type` (frame geometry) from the airframe script.
    pub frame_type: &'static str,
    pub category: AirframeCategory,
    /// SITL model tag (the PX4_SIM_MODEL value that selects this frame at
    /// boot) — posix model airframes only, None for real-vehicle frames.
    pub sim_model: Option<&'static str>,
}

/// The full catalog, sorted by (category, id).
pub static AIRFRAMES: &[Airframe] = &[

    Airframe { id: 4001, name: "Generic Quadcopter", frame_type: "Quadrotor x", category: AirframeCategory::Copter, sim_model: None },
    Airframe { id: 4006, name: "PX4Vision SITL", frame_type: "Quadrotor", category: AirframeCategory::Copter, sim_model: None },
    Airframe { id: 4014, name: "S500 Generic", frame_type: "Quadrotor x", category: AirframeCategory::Copter, sim_model: None },
    Airframe { id: 4015, name: "Holybro S500", frame_type: "Quadrotor x", category: AirframeCategory::Copter, sim_model: None },
    Airframe { id: 4016, name: "PX4 Vision Dev Kit v1", frame_type: "Quadrotor x", category: AirframeCategory::Copter, sim_model: None },
    Airframe { id: 4017, name: "NXP HoverGames", frame_type: "Quadrotor x", category: AirframeCategory::Copter, sim_model: None },
    Airframe { id: 4019, name: "Holybro X500 V2", frame_type: "Quadrotor x", category: AirframeCategory::Copter, sim_model: None },
    Airframe { id: 4020, name: "PX4 Vision Dev Kit v1.5", frame_type: "Quadrotor x", category: AirframeCategory::Copter, sim_model: None },
    Airframe { id: 4041, name: "BetaFPV Beta75X 2S Brushless Whoop", frame_type: "Quadrotor H", category: AirframeCategory::Copter, sim_model: None },
    Airframe { id: 4050, name: "Generic 250 Racer", frame_type: "Quadrotor x", category: AirframeCategory::Copter, sim_model: None },
    Airframe { id: 4052, name: "HolyBro QAV250", frame_type: "Quadrotor x", category: AirframeCategory::Copter, sim_model: None },
    Airframe { id: 4053, name: "Holybro Kopis 2", frame_type: "Quadrotor x", category: AirframeCategory::Copter, sim_model: None },
    Airframe { id: 4061, name: "Advanced Technology Labs (ATL) Mantis EDU", frame_type: "Quadrotor x", category: AirframeCategory::Copter, sim_model: None },
    Airframe { id: 4071, name: "UVify IFO", frame_type: "Quadrotor x", category: AirframeCategory::Copter, sim_model: None },
    Airframe { id: 4073, name: "UVify IFO", frame_type: "Quadrotor x", category: AirframeCategory::Copter, sim_model: None },
    Airframe { id: 4500, name: "COEX Clover 4", frame_type: "Quadrotor x", category: AirframeCategory::Copter, sim_model: None },
    Airframe { id: 4601, name: "Droneblocks DEXI 5", frame_type: "Quadrotor x", category: AirframeCategory::Copter, sim_model: None },
    Airframe { id: 4901, name: "Crazyflie 2.1", frame_type: "Quadrotor x", category: AirframeCategory::Copter, sim_model: None },
    Airframe { id: 5001, name: "Generic Quad + geometry", frame_type: "Quadrotor +", category: AirframeCategory::Copter, sim_model: None },
    Airframe { id: 6001, name: "Generic Hexarotor x geometry", frame_type: "Hexarotor x", category: AirframeCategory::Copter, sim_model: None },
    Airframe { id: 6002, name: "UVify Draco-R", frame_type: "Hexarotor x", category: AirframeCategory::Copter, sim_model: None },
    Airframe { id: 7001, name: "Generic Hexarotor + geometry", frame_type: "Hexarotor +", category: AirframeCategory::Copter, sim_model: None },
    Airframe { id: 8001, name: "Generic Octocopter X geometry", frame_type: "Octorotor x", category: AirframeCategory::Copter, sim_model: None },
    Airframe { id: 8011, name: "6DoF Omnicopter SITL", frame_type: "Quadrotor Wide", category: AirframeCategory::Copter, sim_model: None },
    Airframe { id: 9001, name: "Generic Octocopter + geometry", frame_type: "Octorotor +", category: AirframeCategory::Copter, sim_model: None },
    Airframe { id: 11001, name: "Generic Hexarotor coaxial geometry", frame_type: "Hexarotor Coaxial", category: AirframeCategory::Copter, sim_model: None },
    Airframe { id: 12001, name: "Generic 10\" Octo coaxial geometry", frame_type: "Octorotor Coaxial", category: AirframeCategory::Copter, sim_model: None },
    Airframe { id: 14001, name: "Generic Multirotor with tilt", frame_type: "Tricopter Y+", category: AirframeCategory::Copter, sim_model: None },
    Airframe { id: 16001, name: "Generic Helicopter (Tail ESC)", frame_type: "Helicopter", category: AirframeCategory::Copter, sim_model: None },
    Airframe { id: 24001, name: "Generic Dodecarotor cox geometry", frame_type: "Dodecarotor cox", category: AirframeCategory::Copter, sim_model: None },
    Airframe { id: 1034, name: "Plane SITL", frame_type: "", category: AirframeCategory::Plane, sim_model: None },
    Airframe { id: 2100, name: "Generic Standard Plane", frame_type: "Standard Plane", category: AirframeCategory::Plane, sim_model: None },
    Airframe { id: 2106, name: "Applied Aeronautics Albatross", frame_type: "Plane A-Tail", category: AirframeCategory::Plane, sim_model: None },
    Airframe { id: 3000, name: "Generic Flying Wing", frame_type: "Flying Wing", category: AirframeCategory::Plane, sim_model: None },
    Airframe { id: 4003, name: "Gazebo rc_cessna", frame_type: "Fixedwing", category: AirframeCategory::Plane, sim_model: None },
    Airframe { id: 4008, name: "Advanced Plane SITL", frame_type: "", category: AirframeCategory::Plane, sim_model: None },
    Airframe { id: 4004, name: "Standard VTOL", frame_type: "Standard VTOL", category: AirframeCategory::Vtol, sim_model: None },
    Airframe { id: 4018, name: "Quadrotor + Tailsitter", frame_type: "VTOL Quad Tailsitter", category: AirframeCategory::Vtol, sim_model: None },
    Airframe { id: 13000, name: "Generic Standard VTOL", frame_type: "Standard VTOL", category: AirframeCategory::Vtol, sim_model: None },
    Airframe { id: 13030, name: "Generic Quadplane VTOL Tiltrotor", frame_type: "VTOL Tiltrotor", category: AirframeCategory::Vtol, sim_model: None },
    Airframe { id: 13100, name: "Generic Tiltrotor VTOL", frame_type: "VTOL Tiltrotor", category: AirframeCategory::Vtol, sim_model: None },
    Airframe { id: 13200, name: "Generic VTOL Tailsitter", frame_type: "VTOL Tailsitter", category: AirframeCategory::Vtol, sim_model: None },
    Airframe { id: 1062, name: "ThunderFly TF-R1 UAV Rover", frame_type: "Rover", category: AirframeCategory::Rover, sim_model: None },
    Airframe { id: 4009, name: "Aion Robotics R1 Rover", frame_type: "Rover", category: AirframeCategory::Rover, sim_model: None },
    Airframe { id: 4011, name: "Gazebo lawnmower", frame_type: "Rover", category: AirframeCategory::Rover, sim_model: None },
    Airframe { id: 4012, name: "Rover Ackermann", frame_type: "Rover", category: AirframeCategory::Rover, sim_model: None },
    Airframe { id: 50000, name: "Generic Rover Differential", frame_type: "Rover", category: AirframeCategory::Rover, sim_model: None },
    Airframe { id: 50001, name: "Aion Robotics R1 UGV", frame_type: "Rover", category: AirframeCategory::Rover, sim_model: None },
    Airframe { id: 51000, name: "Generic Rover Ackermann", frame_type: "Rover", category: AirframeCategory::Rover, sim_model: None },
    Airframe { id: 51001, name: "Axial SCX10 2 Trail Honcho", frame_type: "Rover", category: AirframeCategory::Rover, sim_model: None },
    Airframe { id: 52000, name: "Generic Rover Mecanum", frame_type: "Rover", category: AirframeCategory::Rover, sim_model: None },
    Airframe { id: 59000, name: "Generic Ground Vehicle (Deprecated)", frame_type: "Rover", category: AirframeCategory::Rover, sim_model: None },
    Airframe { id: 59001, name: "NXP Cup car: DF Robot GPX (Deprecated)", frame_type: "Rover", category: AirframeCategory::Rover, sim_model: None },
    Airframe { id: 1070, name: "Boat", frame_type: "", category: AirframeCategory::Boat, sim_model: Some("gazebo-classic_boat") },
    Airframe { id: 60000, name: "Generic Underwater Robot", frame_type: "Underwater Robot", category: AirframeCategory::Underwater, sim_model: None },
    Airframe { id: 60001, name: "HippoCampus UUV (Unmanned Underwater Vehicle)", frame_type: "Underwater Robot", category: AirframeCategory::Underwater, sim_model: None },
    Airframe { id: 60002, name: "BlueROV2 (Heavy Configuration)", frame_type: "Vectored 6 DOF UUV", category: AirframeCategory::Underwater, sim_model: None },
    Airframe { id: 2507, name: "Cloudship", frame_type: "Airship", category: AirframeCategory::Other, sim_model: None },
    Airframe { id: 4002, name: "Gazebo x500 depth", frame_type: "Quadrotor", category: AirframeCategory::Other, sim_model: None },
    Airframe { id: 4005, name: "Gazebo x500 vision", frame_type: "Quadrotor", category: AirframeCategory::Other, sim_model: None },
    Airframe { id: 4010, name: "Gazebo x500 mono cam", frame_type: "Quadrotor", category: AirframeCategory::Other, sim_model: None },
    Airframe { id: 4013, name: "Gazebo x500 lidar 2d", frame_type: "Quadrotor", category: AirframeCategory::Other, sim_model: None },
    Airframe { id: 4021, name: "Gazebo x500 with downward optical flow and distance sensor", frame_type: "Quadrotor", category: AirframeCategory::Other, sim_model: None },
    Airframe { id: 17001, name: "ThunderFly TF-G1", frame_type: "Autogyro", category: AirframeCategory::Other, sim_model: None },
    Airframe { id: 17002, name: "ThunderFly Auto-G2", frame_type: "Autogyro", category: AirframeCategory::Other, sim_model: None },
    Airframe { id: 17003, name: "ThunderFly TF-G2", frame_type: "Autogyro", category: AirframeCategory::Other, sim_model: None },
    Airframe { id: 18001, name: "ThunderFly balloon TF-B1", frame_type: "Balloon", category: AirframeCategory::Other, sim_model: None },
    Airframe { id: 71002, name: "3DoF Spacecraft Model", frame_type: "2D Freeflyer with 8 thrusters - Planar motion", category: AirframeCategory::Other, sim_model: None },
    Airframe { id: 1010, name: "3DR Iris Quadrotor SITL (Optical Flow)", frame_type: "Quadrotor Wide", category: AirframeCategory::Simulator, sim_model: Some("gazebo-classic_iris_opt_flow") },
    Airframe { id: 1011, name: "3DR Iris Quadrotor SITL (irlock)", frame_type: "Quadrotor Wide", category: AirframeCategory::Simulator, sim_model: Some("gazebo-classic_iris_irlock") },
    Airframe { id: 1012, name: "3DR Iris Quadrotor SITL (rplidar)", frame_type: "Quadrotor Wide", category: AirframeCategory::Simulator, sim_model: Some("gazebo-classic_iris_rplidar") },
    Airframe { id: 1013, name: "3DR Iris Quadrotor SITL (Vision)", frame_type: "Quadrotor Wide", category: AirframeCategory::Simulator, sim_model: Some("gazebo-classic_iris_vision") },
    Airframe { id: 1015, name: "3DR Iris Quadrotor with a depth camera (forward-facing)", frame_type: "Quadrotor Wide", category: AirframeCategory::Simulator, sim_model: Some("gazebo-classic_iris_depth_camera") },
    Airframe { id: 1016, name: "3DR Iris Quadrotor with a depth camera (downward-facing)", frame_type: "Quadrotor Wide", category: AirframeCategory::Simulator, sim_model: Some("gazebo-classic_iris_downward_depth_camera") },
    Airframe { id: 1017, name: "3DR Iris Quadrotor SITL (Optical Flow)", frame_type: "Quadrotor Wide", category: AirframeCategory::Simulator, sim_model: Some("gazebo-classic_iris_opt_flow_mockup") },
    Airframe { id: 1019, name: "3DR Iris Quadrotor SITL (Dual GPS)", frame_type: "Quadrotor Wide", category: AirframeCategory::Simulator, sim_model: Some("gazebo-classic_iris_dual_gps") },
    Airframe { id: 1021, name: "Hippocampus UUV", frame_type: "", category: AirframeCategory::Simulator, sim_model: Some("gazebo-classic_uuv_hippocampus") },
    Airframe { id: 1022, name: "BlueROV2 Heavy Configuration", frame_type: "", category: AirframeCategory::Simulator, sim_model: Some("gazebo-classic_uuv_bluerov2_heavy") },
    Airframe { id: 1030, name: "Plane SITL", frame_type: "", category: AirframeCategory::Simulator, sim_model: Some("gazebo-classic_plane") },
    Airframe { id: 1031, name: "Plane SITL with camera", frame_type: "", category: AirframeCategory::Simulator, sim_model: Some("gazebo-classic_plane_cam") },
    Airframe { id: 1032, name: "Plane SITL with catapult", frame_type: "", category: AirframeCategory::Simulator, sim_model: Some("gazebo-classic_plane_catapult") },
    Airframe { id: 1033, name: "Plane SITL", frame_type: "", category: AirframeCategory::Simulator, sim_model: Some("jsbsim_rascal") },
    Airframe { id: 1035, name: "Plane SITL", frame_type: "", category: AirframeCategory::Simulator, sim_model: Some("gazebo-classic_techpod") },
    Airframe { id: 1036, name: "Plane SITL", frame_type: "", category: AirframeCategory::Simulator, sim_model: Some("jsbsim_malolo") },
    Airframe { id: 1037, name: "Plane SITL", frame_type: "", category: AirframeCategory::Simulator, sim_model: Some("gazebo-classic_believer") },
    Airframe { id: 1038, name: "Plane SITL with catapult", frame_type: "", category: AirframeCategory::Simulator, sim_model: Some("gazebo-classic_glider") },
    Airframe { id: 1039, name: "Advanced Plane SITL", frame_type: "", category: AirframeCategory::Simulator, sim_model: Some("gazebo-classic_advanced_plane") },
    Airframe { id: 1040, name: "Standard VTOL", frame_type: "Standard VTOL", category: AirframeCategory::Simulator, sim_model: Some("gazebo-classic_standard_vtol") },
    Airframe { id: 1041, name: "Quadrotor + Tailsitter", frame_type: "VTOL Quad Tailsitter", category: AirframeCategory::Simulator, sim_model: Some("gazebo-classic_tailsitter") },
    Airframe { id: 1042, name: "VTOL Tiltrotor", frame_type: "VTOL Tiltrotor", category: AirframeCategory::Simulator, sim_model: Some("gazebo-classic_tiltrotor") },
    Airframe { id: 1043, name: "Standard VTOL", frame_type: "Standard VTOL", category: AirframeCategory::Simulator, sim_model: Some("gazebo-classic_standard_vtol_drop") },
    Airframe { id: 1044, name: "Plane SITL with downward facing LIDAR.", frame_type: "", category: AirframeCategory::Simulator, sim_model: Some("gazebo-classic_plane_lidar") },
    Airframe { id: 1045, name: "Quadrotor + Tailsitter", frame_type: "VTOL Quad Tailsitter", category: AirframeCategory::Simulator, sim_model: Some("gazebo-classic_quadtailsitter") },
    Airframe { id: 1060, name: "Rover", frame_type: "", category: AirframeCategory::Simulator, sim_model: Some("gazebo-classic_rover") },
    Airframe { id: 1061, name: "Aion Robotics R1 Rover", frame_type: "Rover", category: AirframeCategory::Simulator, sim_model: Some("gazebo-classic_r1_rover") },
    Airframe { id: 3010, name: "Quadrotor SITL model for JSBSim", frame_type: "Quadrotor Wide", category: AirframeCategory::Simulator, sim_model: Some("jsbsim_quadrotor_x") },
    Airframe { id: 3011, name: "Hexacopter SITL model for JSBSim", frame_type: "Hexarotor x", category: AirframeCategory::Simulator, sim_model: Some("jsbsim_hexarotor_x") },
    Airframe { id: 6011, name: "Typhoon H480 SITL", frame_type: "Hexarotor x", category: AirframeCategory::Simulator, sim_model: Some("gazebo-classic_typhoon_h480") },
    Airframe { id: 10015, name: "3DR Iris Quadrotor SITL", frame_type: "Quadrotor Wide", category: AirframeCategory::Simulator, sim_model: Some("gazebo-classic_iris") },
    Airframe { id: 10016, name: "Generic Iris Quadrotor SITL", frame_type: "Quadrotor Wide", category: AirframeCategory::Simulator, sim_model: Some("none_iris") },
    Airframe { id: 10017, name: "3DR Iris Quadrotor SITL jMAVSim", frame_type: "Quadrotor Wide", category: AirframeCategory::Simulator, sim_model: Some("jmavsim_iris") },
    Airframe { id: 10018, name: "3DR Iris Quadrotor SITL (foggy_lidar)", frame_type: "Quadrotor Wide", category: AirframeCategory::Simulator, sim_model: Some("gazebo-classic_iris_foggy_lidar") },
    Airframe { id: 10019, name: "6DoF Omnicopter SITL", frame_type: "Quadrotor Wide", category: AirframeCategory::Simulator, sim_model: Some("gazebo-classic_omnicopter") },
    Airframe { id: 10030, name: "PX4Vision SITL", frame_type: "Quadrotor", category: AirframeCategory::Simulator, sim_model: Some("gazebo-classic_px4vision") },
    Airframe { id: 10040, name: "QuadrotorX SITL for SIH", frame_type: "Quadrotor", category: AirframeCategory::Simulator, sim_model: Some("sihsim_quadx") },
    Airframe { id: 10041, name: "Plane SITL for SIH", frame_type: "Plane", category: AirframeCategory::Simulator, sim_model: Some("sihsim_airplane") },
    Airframe { id: 10042, name: "SIH Tailsitter Duo", frame_type: "VTOL", category: AirframeCategory::Simulator, sim_model: Some("sihsim_xvert") },
    Airframe { id: 10043, name: "SIH Standard VTOL", frame_type: "Simulation", category: AirframeCategory::Simulator, sim_model: Some("sihsim_standard_vtol") },
    Airframe { id: 71001, name: "6DoF Spacecraft Model", frame_type: "Freeflyer with 8 thrusters", category: AirframeCategory::Simulator, sim_model: Some("gazebo-classic_spacecraft_dart") },
];
