//! Golden-vector tests: byte-exact round-trips against frames generated by
//! pymavlink 2.4.49 (v2.0 common dialect). The fixtures in
//! `golden_mavlink.json` were produced by `scripts/gen_golden.py` during
//! bring-up; they pin the wire contract (field order, CRC extra, trailing
//! zero trimming, framing) for both encode and decode.

use fleet_mavlink::frame::{crc_extra, Decoder, Frame};
use fleet_mavlink::messages::{
    decode_event, Attitude, BatteryStatus, CommandAck, CommandLong, GlobalPositionInt, Heartbeat,
    HomePosition, LocalPositionNed, ParamRequestList, ParamRequestRead, ParamSet, ParamValue, Ping,
    SetPositionTargetLocalNed, StatusText, SysStatus, TelemetryEvent,
};
use serde_json::Value;

#[path = "common.rs"]
mod common;

fn fixtures() -> Vec<Value> {
    let raw = include_str!("golden_mavlink.json");
    serde_json::from_str(raw).expect("valid golden fixtures")
}

/// Decode every fixture with our decoder (CRC must verify) and re-encode it
/// with our encoder: the bytes must be identical to pymavlink's.
#[test]
fn golden_roundtrip_byte_exact() {
    for v in fixtures() {
        let name = v["name"].as_str().unwrap();
        let hex = v["hex"].as_str().unwrap();
        let sysid = v["sysid"].as_u64().unwrap() as u8;
        let compid = v["compid"].as_u64().unwrap() as u8;
        let bytes = common::hex_decode(hex);
        let mut d = Decoder::new();
        d.push(&bytes);
        let frame = d
            .next_frame()
            .unwrap_or_else(|| panic!("{name}: no frame decoded"));
        assert!(frame.crc_ok, "{name}: CRC mismatch");
        assert_eq!(frame.sysid, sysid, "{name}: sysid");
        assert_eq!(frame.compid, compid, "{name}: compid");
        assert_eq!(frame.seq, 0, "{name}: seq (fixtures use seq 0)");
        assert!(d.next_frame().is_none(), "{name}: extra frames");

        // Re-encode with the same header fields; must be byte-identical.
        let extra = crc_extra(frame.msgid).unwrap_or(0);
        let out = frame.encode_v2(0, extra);
        assert_eq!(out, bytes, "{name}: re-encode differs from pymavlink bytes");
    }
}

#[test]
fn golden_decoded_field_values() {
    for v in fixtures() {
        let name = v["name"].as_str().unwrap();
        let bytes = common::hex_decode(v["hex"].as_str().unwrap());
        let mut d = Decoder::new();
        d.push(&bytes);
        let frame = d.next_frame().unwrap();
        let ev = decode_event(&frame).unwrap();
        match (name, ev) {
            ("HEARTBEAT_gcs", TelemetryEvent::Heartbeat { base_mode, custom_mode, .. }) => {
                assert_eq!((base_mode, custom_mode), (0, 0));
            }
            ("HEARTBEAT_px4", TelemetryEvent::Heartbeat { base_mode, custom_mode, sysid, compid, .. }) => {
                assert_eq!((sysid, compid, base_mode, custom_mode), (2, 1, 209, (4 << 16) | (3 << 24)));
            }
            ("COMMAND_LONG_domode_offboard", TelemetryEvent::Unknown { .. }) => {
                // COMMAND_LONG is not a TelemetryEvent variant; verify via
                // the typed unpack below.
            }
            ("COMMAND_ACK", TelemetryEvent::CommandAck { command, result, target_system, target_component, .. }) => {
                assert_eq!((command, result, target_system, target_component), (176, 0, 255, 190));
            }
            ("ATTITUDE", TelemetryEvent::Attitude { time_boot_ms, roll, pitch, yaw, .. }) => {
                assert_eq!(time_boot_ms, 1000);
                assert_eq!((roll, pitch, yaw), (0.1, -0.2, 3.0));
            }
            ("LOCAL_POSITION_NED", TelemetryEvent::LocalPositionNed { x, y, z, vx, vy, vz, .. }) => {
                assert_eq!((x, y, z), (1.5, -2.5, -10.0));
                assert_eq!((vx, vy, vz), (0.1, 0.2, -0.3));
            }
            ("GLOBAL_POSITION_INT", TelemetryEvent::GlobalPositionInt { lat, lon, alt, relative_alt }) => {
                assert_eq!((lat, lon, alt, relative_alt), (473977000, 85455000, 50000, 48000));
            }
            ("SYS_STATUS", TelemetryEvent::SysStatus { battery_remaining_pct, voltage_battery_mv, current_battery_ca }) => {
                assert_eq!((battery_remaining_pct, voltage_battery_mv, current_battery_ca), (80, 11800, -1500));
            }
            ("BATTERY_STATUS", TelemetryEvent::BatteryStatus { battery_remaining_pct, voltage_mv, current_battery_ca }) => {
                assert_eq!((battery_remaining_pct, voltage_mv, current_battery_ca), (75, 11800, -1500));
            }
            ("HOME_POSITION", TelemetryEvent::HomePosition { x, y, z, lat, lon, alt }) => {
                assert_eq!((x, y, z), (0.0, 0.0, 0.0));
                assert_eq!((lat, lon, alt), (473977000, 85455000, 50000));
            }
            ("STATUSTEXT", TelemetryEvent::StatusText { severity, text }) => {
                assert_eq!(severity, 4);
                assert_eq!(text, "hello fleet");
            }
            ("PING", TelemetryEvent::Ping { time_usec, seq }) => {
                assert_eq!((time_usec, seq), (1234567890, 0));
            }
            ("PARAM_VALUE_echo", TelemetryEvent::ParamValue { param_id, value, param_type, param_count, param_index, .. }) => {
                // golden-pinned wire order: value@0, count@4, index@6,
                // id@8, type@24 (see ADR-0016; the v0.1 XML-order decoder
                // could never confirm a write).
                assert_eq!(param_id, "NAV_DLL_ACT");
                assert_eq!(value, 0.0);
                assert_eq!(param_type, 9);
                assert_eq!(param_count, 722);
                assert_eq!(param_index, 101);
            }
            ("SET_POSITION_TARGET_LOCAL_NED_position", TelemetryEvent::Unknown { .. }) => {}
            ("SET_POSITION_TARGET_LOCAL_NED_velocity", TelemetryEvent::Unknown { .. }) => {}
            (_, TelemetryEvent::Unknown { .. }) => {}
            (n, e) => panic!("{n}: unexpected event {e:?}"),
        }
    }
}

/// Typed verification for the outbound GCS messages that are not
/// `TelemetryEvent` variants: command/setpoint set plus the param
/// protocol's request sides (request-list, request-read, param-set).
#[test]
fn golden_typed_outbound_messages() {
    for v in fixtures() {
        let name = v["name"].as_str().unwrap();
        if !name.starts_with("COMMAND_LONG")
            && !name.starts_with("SET_POSITION_TARGET")
            && !name.starts_with("PARAM_")
        {
            continue;
        }
        let bytes = common::hex_decode(v["hex"].as_str().unwrap());
        let mut d = Decoder::new();
        d.push(&bytes);
        let frame = d.next_frame().unwrap();
        match name {
            "COMMAND_LONG_setmsginterval" => {
                let m = CommandLong::unpack(&frame.payload).unwrap();
                assert_eq!(m.command, 511);
                assert_eq!(m.target_system, 1);
                assert_eq!((m.params[0], m.params[1]), (32.0, 20000.0));
            }
            "COMMAND_LONG_domode_offboard" => {
                let m = CommandLong::unpack(&frame.payload).unwrap();
                assert_eq!(m.command, 176);
                assert_eq!(m.params[0], 1.0); // MAV_MODE_FLAG_CUSTOM_ENABLED
                assert_eq!(m.params[1], (6 << 16) as f32); // OFFBOARD word (header layout)
            }
            "COMMAND_LONG_domode_rtl" => {
                let m = CommandLong::unpack(&frame.payload).unwrap();
                assert_eq!(m.params[1], ((4 << 16) | (5 << 24)) as f32); // header union layout
            }
            "COMMAND_LONG_domode_land" => {
                let m = CommandLong::unpack(&frame.payload).unwrap();
                assert_eq!(m.params[1], ((4 << 16) | (6 << 24)) as f32);
            }
            "COMMAND_LONG_arm" => {
                let m = CommandLong::unpack(&frame.payload).unwrap();
                assert_eq!((m.command, m.params[0]), (400, 1.0));
            }
            "COMMAND_LONG_takeoff" => {
                let m = CommandLong::unpack(&frame.payload).unwrap();
                assert_eq!((m.command, m.params[6]), (22, 12.0));
            }
            "SET_POSITION_TARGET_LOCAL_NED_position" => {
                let m = SetPositionTargetLocalNed::unpack(&frame.payload).unwrap();
                assert_eq!(m.type_mask, 2552); // POSITION_ONLY
                assert_eq!((m.x, m.y, m.z), (10.0, -20.0, -30.0));
                assert_eq!(m.yaw, 1.5);
                assert_eq!(m.coordinate_frame, 1);
                assert_eq!((m.target_system, m.target_component), (1, 1));
            }
            "SET_POSITION_TARGET_LOCAL_NED_velocity" => {
                let m = SetPositionTargetLocalNed::unpack(&frame.payload).unwrap();
                assert_eq!(m.type_mask, 1479); // VELOCITY_YAWRATE
                assert_eq!((m.vx, m.vy, m.vz), (1.0, 2.0, -0.5));
                assert_eq!(m.yaw_rate, 0.25);
            }
            "PARAM_REQUEST_LIST" => {
                let m = ParamRequestList::unpack(&frame.payload).unwrap();
                assert_eq!((m.target_system, m.target_component), (1, 1));
            }
            "PARAM_REQUEST_READ" => {
                let m = ParamRequestRead::unpack(&frame.payload).unwrap();
                assert_eq!(m.param_index, -1);
                assert_eq!((m.target_system, m.target_component), (1, 1));
                assert_eq!(m.param_id_string(), "BAT_N_CELLS");
            }
            "PARAM_SET_nav_dll_act" => {
                // re-pack our typed PARAM_SET and compare payload bytes
                // to pymavlink's: byte-exact wire order proof.
                let ours = ParamSet::from_str("NAV_DLL_ACT", 0.0, 1, 1);
                assert_eq!(ours.pack(), frame.payload);
            }
            _ => {}
        }
    }
}

/// Every struct's pack->unpack round-trip must be lossless (including
/// trailing-zero-trim tolerance).
#[test]
fn typed_pack_unpack_roundtrips() {
    let cases: Vec<(&'static str, Vec<u8>)> = vec![
        ("heartbeat", Heartbeat { custom_mode: 0x40300, mavtype: 2, autopilot: 12, base_mode: 209, system_status: 4, mavlink_version: 3 }.pack()),
        ("attitude", Attitude { time_boot_ms: 1, roll: 0.5, pitch: -0.5, yaw: 3.1, rollspeed: 0.1, pitchspeed: 0.2, yawspeed: 0.3 }.pack()),
        ("local_pos", LocalPositionNed { time_boot_ms: 2, x: 1.0, y: 2.0, z: -3.0, vx: 0.1, vy: 0.2, vz: -0.3 }.pack()),
        ("global_pos", GlobalPositionInt { time_boot_ms: 3, lat: 473977000, lon: 85455000, alt: 50000, relative_alt: 49000, vx: 10, vy: -20, vz: 30, hdg: 18000 }.pack()),
        ("sys_status", SysStatus { load: 500, voltage_battery_mv: 11800, current_battery_ca: -1500, battery_remaining_pct: 80 }.pack()),
        ("battery", BatteryStatus { voltages_mv: [11800, 0, 0, 0, 0, 0, 0, 0, 0, 0], current_battery_ca: -1500, id: 0, battery_remaining_pct: 75, temperature_cdegc: 2500 }.pack()),
        ("statustext", StatusText { severity: 4, text: "abc".into(), id: 0, chunk_seq: 0 }.pack()),
        ("home", HomePosition { latitude: 473977000, longitude: 85455000, altitude: 50000, x: 1.0, y: 2.0, z: 3.0 }.pack()),
        ("ping", Ping { time_usec: 7, seq: 9, target_system: 1, target_component: 1 }.pack()),
        ("cmd_long", CommandLong { target_system: 1, target_component: 1, command: 400, confirmation: 1, params: [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0] }.pack()),
        ("cmd_ack", CommandAck { command: 176, result: 0, progress: 255, result_param2: 0, target_system: 255, target_component: 190 }.pack()),
        ("setpoint", SetPositionTargetLocalNed { time_boot_ms: 99, target_system: 1, target_component: 1, coordinate_frame: 1, type_mask: 2552, x: 1.0, y: 2.0, z: -3.0, yaw: 1.5, ..Default::default() }.pack()),
    ];
    let trim = |mut b: Vec<u8>| {
        while b.last() == Some(&0) {
            b.pop();
        }
        b
    };
    for (name, bytes) in cases {
        let trimmed = trim(bytes.clone());
        // Decode the trimmed payload (protocol-legal), re-pack, re-trim and
        // compare to the trimmed original: the wire-level round trip.
        let repacked = match name {
            "heartbeat" => Heartbeat::unpack(&trimmed).unwrap().pack(),
            "attitude" => Attitude::unpack(&trimmed).unwrap().pack(),
            "local_pos" => LocalPositionNed::unpack(&trimmed).unwrap().pack(),
            "global_pos" => GlobalPositionInt::unpack(&trimmed).unwrap().pack(),
            "sys_status" => SysStatus::unpack(&trimmed).unwrap().pack(),
            "battery" => BatteryStatus::unpack(&trimmed).unwrap().pack(),
            "statustext" => {
                // STATUSTEXT pads its fixed text[50] array; trimming can cut
                // into it, so the property is unpack(pack(m)) == m.
                let m = StatusText::unpack(&trimmed).unwrap();
                assert_eq!(StatusText::unpack(&m.pack()).unwrap(), m, "{name}");
                assert_eq!(m.text, "abc");
                m.pack()
            }
            "home" => HomePosition::unpack(&trimmed).unwrap().pack(),
            "ping" => Ping::unpack(&trimmed).unwrap().pack(),
            "cmd_long" => CommandLong::unpack(&trimmed).unwrap().pack(),
            "cmd_ack" => CommandAck::unpack(&trimmed).unwrap().pack(),
            "setpoint" => SetPositionTargetLocalNed::unpack(&trimmed).unwrap().pack(),
            _ => unreachable!(),
        };
        assert_eq!(trim(repacked), trimmed, "{name}");
    }
}

/// The setpoint masks the link transmits must be the fleet-modes constants.
#[test]
fn setpoint_masks_match_fleet_modes() {
    for v in fixtures() {
        let name = v["name"].as_str().unwrap();
        if name == "SET_POSITION_TARGET_LOCAL_NED_position" {
            let bytes = common::hex_decode(v["hex"].as_str().unwrap());
            let mut d = Decoder::new();
            d.push(&bytes);
            let f = d.next_frame().unwrap();
            let m = SetPositionTargetLocalNed::unpack(&f.payload).unwrap();
            assert_eq!(m.type_mask, fleet_modes::POSITION_ONLY);
        }
        if name == "SET_POSITION_TARGET_LOCAL_NED_velocity" {
            let bytes = common::hex_decode(v["hex"].as_str().unwrap());
            let mut d = Decoder::new();
            d.push(&bytes);
            let f = d.next_frame().unwrap();
            let m = SetPositionTargetLocalNed::unpack(&f.payload).unwrap();
            assert_eq!(m.type_mask, fleet_modes::VELOCITY_YAWRATE);
        }
    }
}
